apiVersion: v1
kind: Pod

metadata:
  name: my-pod-webserver
  labels:
    app: my-app
    tier: front

spec:
  containers:
    - name: my-container-nginx
      image: nginx
      ports:
        - containerPort: 80